# Generated by Django 5.1.1 on 2024-10-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_fee_amount_remove_fee_level_feeamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeamount',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.fee'),
        ),
    ]
