# Generated by Django 5.1.1 on 2024-09-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecode',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.level'),
        ),
    ]
