# Generated by Django 5.1.1 on 2024-09-16 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.level')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.RemoveField(
            model_name='coursecode',
            name='department',
        ),
        migrations.RemoveField(
            model_name='coursecode',
            name='level',
        ),
        migrations.RemoveField(
            model_name='coursecode',
            name='semester',
        ),
        migrations.DeleteModel(
            name='CourseLevel',
        ),
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='program',
        ),
        migrations.DeleteModel(
            name='CourseCode',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
