# Generated by Django 5.1.1 on 2024-09-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_session_remove_coursecode_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
    ]
