# Generated by Django 5.1.1 on 2024-10-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.faculty'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
