# Generated by Django 5.1.1 on 2024-10-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_faculty_options_department_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.faculty'),
            preserve_default=False,
        ),
    ]
