# Generated by Django 5.1.1 on 2024-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_department_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['admission_year']},
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
