# Generated by Django 5.1.1 on 2024-10-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentprofile_gender_studentprofile_nationality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
    ]
